{"errorMessage": "('Something wrong happened', b'{\\n  \"timestamp\" : \"2021-10-18T16:28:51.628+00:00\",\\n  \"status\" : 500,\\n  \"error\" : \"Internal Server Error\",\\n  \"message\" : \"query did not return a unique result: 3; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 3\",\\n  \"path\" : \"/api/v1/patient/PT0523957/daresults/recent\"\\n}', 500, 'https://patient-portal-service.autoimmune.cloud/api/v1/patient/PT0523957/daresults/recent')", "errorType": "Exception", "stackTrace": ["  File \"/var/task/scheduled/echo_update_result_status.py\", line 19, in handle\n    result_status['test_report_event_id']\n", "  File \"/var/task/scheduled/echo_update_result_status.py\", line 30, in deliver_result_status\n    raise Exception('Something wrong happened', response, status_code, url)\n"]}